### PR TITLE
Add scrypt.encode_utf8()

### PR DESCRIPTION
**Pull request by makersphereLabs**
Add `scrypt.encode_utf8()` function to fix JS errors in Firefox and Safari.

### CODE REVIEW

**Comment by atoponce** [comment]
Tested, and confirmed in Firefox. Without the string being an encoded scrypt object returning a Uint8Array, while Chrome/Chromium has no problem with the raw string, Firefox errors out unless properly encoded.

As such, the code should be:

```
code = encode(scrypt.crypto_scrypt(scrypt.encode_utf8(string),
                                   scrypt.encode_utf8(salt),
                                   N, r, p, L));
```

**Comment by atoponce** [comment]
I noticed that you increased the key length to 40 bytes. That's 320-bits for a 76-bit emoji "story". It's a bit long. 12-bytes (96-bits) would be sufficient, although it's certainly copy/paste, so it shouldn't matter anyway.

**Comment by makersphereLabs** [comment]
@atoponce Haha, alright! 😉
Will update the key length to 12 bytes and then merge to `master`.

**Comment by makersphereLabs** [comment]
Ok, we're ready to merge.
Next, we need to **fix the UI** and add some **unique salt** #12 . 😉

**Pull request merged**
